### ISSUE TITLE
Word wrap does not work

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#26]
Max print width may be ignored with spaces (and possibly also tabs but it's hard to tell because of #25):

![image](https://user-images.githubusercontent.com/20878432/106390944-24c09f80-63eb-11eb-8036-dc2e807df6df.png)

---

Print width is configured as 120 in all screenshots. The column ruler sits at 120 as well.

**Comment by hosseinmd** [comment]
We are not too strict for print width on the end line of paragraphs. 
We decided about that on this https://github.com/hosseinmd/prettier-plugin-jsdoc/issues/8#issuecomment-691631278

**Comment by hosseinmd** [comment]
This is a description which broke in two line:
<img width="726" alt="Screen Shot 2021-02-02 at 9 19 53 PM" src="https://user-images.githubusercontent.com/45505767/106641531-8f650d00-659c-11eb-8a05-1b71c7e092aa.png">
If we remove a few words from that:
<img width="726" alt="Screen Shot 2021-02-02 at 9 21 49 PM" src="https://user-images.githubusercontent.com/45505767/106641730-c9ceaa00-659c-11eb-99ad-70d15fb0bbb3.png">
So that is not good, we don't break lines like this:
<img width="813" alt="Screen Shot 2021-02-02 at 9 23 24 PM" src="https://user-images.githubusercontent.com/45505767/106642142-3b0e5d00-659d-11eb-84cc-b5a4928bd6a3.png">
