### ISSUE TITLE
Don't remove default values of optional parameters

### ISSUE THREAD

**Issue by RunDevelopment** [hosseinmd/prettier-plugin-jsdoc#28]
For some reason, this plugin removes the default values of optional parameters and simply adds a note with the default value.

This is a problem because JSDoc's static site generator cannot detect default values this way and is unable to add them to the parameter table. [This example](https://prismjs.com/docs/Prism.html#.highlightAllUnder) has a *Default* column that is missing after formatting the source code with this plugin.

Please either remove this feature or add an option to turn it off. It is interfering with JSDoc.

### Example

Before:
![image](https://user-images.githubusercontent.com/20878432/106391781-4e7bc580-63ef-11eb-8f9b-4c9d4a0a947c.png)

After:
![image](https://user-images.githubusercontent.com/20878432/106391743-373cd800-63ef-11eb-8929-fc54bb8a043c.png)

**Comment by hosseinmd** [comment]
This is because default value is not recognized by VS Code.
For Example:

<img width="698" alt="Screen Shot 2021-01-31 at 9 09 00 PM" src="https://user-images.githubusercontent.com/45505767/106392851-06699c80-6409-11eb-89da-670dad7d1be8.png">


I this Picture some one which using that function never know which params has what default value, so that will be converted to:

<img width="686" alt="Screen Shot 2021-01-31 at 9 13 24 PM" src="https://user-images.githubusercontent.com/45505767/106392897-2ef19680-6409-11eb-846e-00a0a58f3f12.png">

**Comment by RunDevelopment** [comment]
So this feature was added to work-around a shortcoming of TypeScript's language server. That's reasonable. However, I still think that it's not a good idea to remove the default values. As I said, it interferes with JSDoc.

I'm not sure what the best solution is here. My proposed option to turn this off will work but it won't solve the underlying problem.

**Comment by hosseinmd** [comment]
I think the best option is to keep both, if there is a way to do it.

**Comment by RunDevelopment** [comment]
> if there is a way to do it

Well, this plugin could detect if the param description ends with a `Default value is <value>` sentence and automatically update/add it if necessary.
