### ISSUE TITLE
Is there any way to preserve formatted text?

### ISSUE THREAD

**Issue by melink14** [hosseinmd/prettier-plugin-jsdoc#5]
For example, I sometimes include lists in my jsdoc descriptions which currently get collapsed by the formatter:

```
/**
 * Does the following things:
 *    1. Thing 1
 *    2. Thing 2
 *    3. Thing 3
 */
```

I'm not sure of a good generic way to handle this. Maybe detecting HTML or Markdown syntax to know that something shouldn't be formatted. Or recognizing some kind of <pre> tag which ignores formatting.

Disabling the formatter for just that comment would also be a solution but I wasn't able to figure out the syntax just yet.

Thanks as always!

**Comment by hosseinmd** [comment]
I have an idea. But I don't know if this is good.
```js
/**
 * Does the following things:
 *
 * @col 1. Thing 1
 * @col 2. Thing 2
 * @col 3. Thing 3
 */
```

**Comment by melink14** [comment]
That's not bad, but my linter will cry if I use non valid tags in jsdoc. :)

I think this should be doable with some combination of prettier-ignore so I will try this weekend!

**Comment by hosseinmd** [comment]
I found some stuff about VSC intellisense. VSC ignoring \n of description when showing that in popup.
For example:
<img width="637" alt="Screen Shot 2020-08-27 at 6 52 55 PM" src="https://user-images.githubusercontent.com/45505767/91454854-a76e8d00-e896-11ea-9f4d-df13305733ab.png">

vsc show that like
 
<img width="727" alt="Screen Shot 2020-08-27 at 6 54 50 PM" src="https://user-images.githubusercontent.com/45505767/91455003-d258e100-e896-11ea-8137-2c7ebf729783.png">

But when I add tow new line character vsc showing that like this.
<img width="730" alt="Screen Shot 2020-08-27 at 6 56 29 PM" src="https://user-images.githubusercontent.com/45505767/91455210-0df3ab00-e897-11ea-836c-a802f0553aaf.png">
I think we should use this pattern to improve this plugin. Because with this method, we become more compatible with vsc

**Comment by hosseinmd** [comment]
Your description will be something like this.
<img width="331" alt="Screen Shot 2020-08-27 at 7 04 26 PM" src="https://user-images.githubusercontent.com/45505767/91456234-434cc880-e898-11ea-8e87-ed2336c01dba.png">
VSC showing that this way:
<img width="341" alt="Screen Shot 2020-08-27 at 7 04 38 PM" src="https://user-images.githubusercontent.com/45505767/91456361-67a8a500-e898-11ea-86ed-fa6f8ef0e2e9.png">

**Comment by hosseinmd** [comment]
Paragraph separation has been implemented and published in the 0.1.0 version.

**Comment by hosseinmd** [comment]
@melink14 Thank you

**Comment by melink14** [comment]
Thanks for the update. I can confirm the extra newlines definitely work.
It's a bit verbose and it's also too bad that indentation gets removed, though vscode hover treats it OK.

I was comparing that formatting to clang-format which seems to keep newlines intact which is the opposite end of the spectrum. clang-format is nice but I think your work here will allow me to continue using prettier!

👍🏾

**Comment by hosseinmd** [comment]
Issue with Line starting space resolved. https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/73adaf134d26ff274e88516d8a01800d762640e7
You can use this format now
```js
/**
 * Does the following things:
 *     1. Thing 1
 *     2. Thing 2
 *     3. Thing 3
 */
```
But this is best if you want to have VSC Intelisense benefits.
```js
/**
 * Does the following things:
 *
 *     1. Thing 1
 *     2. Thing 2
 *     3. Thing 3
 */
```

**Comment by melink14** [comment]
Thanks! This is definitely going to be useful.
